name: Trivy

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    name: fs scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@d2a0b60797ff03db6132bd4e2b293f9b37081297 # master
        with:
          scan-type: fs
          scanners: vuln,secret,misconfig
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@3ea06614dafe36dec890db3446326e0d40ce53d4 # v3
        if: always()
        with:
          sarif_file: trivy-results.sarif
